### ISSUE TITLE
Same country name for Virgin Islands

### ISSUE THREAD

**Issue by rbrazhnyk** [ecrmnn/iso-3166-1#9]
Thanks, for the library!
We use it on a frontend as a data source of country names and Virgin Islands meets twice as a name which is ambiguous.

The official name of the British territory is the `Virgin Islands`, and the official name of the U.S. territory is the `Virgin Islands of the United States` (taken from [wiki](https://en.wikipedia.org/wiki/Virgin_Islands)).

Link to [PR](https://github.com/ecrmnn/iso-3166-1/pull/8).

Many thanks!
I hope the update will be published soon.

**Comment by ecrmnn** [comment]
Closed in https://github.com/ecrmnn/iso-3166-1/commit/156a7f1d2f4ea3dce03d69b6e4b6e5af96b33ff5
